### ISSUE TITLE
Custom stacking size doesn't seem to work and disables the plugin entirely

### ISSUE THREAD

**Issue by yepikaiye** [ploppyperson/StackMob-5#296]
# # Some options can be modified for specific entity types. An example is shown below. Remove comments to see this in action.
# # Options and sections with a (*) in the comment preceding cannot be overridden.
 custom:
  # The entity type
  CHICKEN:
    # The option to override. This should be the same as it appears above.
    stack:
      max-size: 10
#  SKELETON:
#    # Entities can also inherit options from other entities, using the 'clone' option preceded by the entity type to clone.
#    clone: CREEPER
#    # The cloned custom options can still be overridden.
#    stack:
#      max-size: 5

https://i.imgur.com/GLGGapc.png

https://i.imgur.com/y38ZEVO.png (Zombie isn't even configured but it affects all other mobs too)

**Comment by ploppyperson** [comment]
Can you put your config on something like pastebin?

**Comment by yepikaiye** [comment]
Yea sure: https://pastebin.com/9u87EnAT

**Comment by ploppyperson** [comment]
This doesn't seem to have anything in the custom section?

**Comment by yepikaiye** [comment]
Ah yea I disabled it because it didn't work, I'll send the one when I had when I tested it, my apologies

https://pastebin.com/xnGi7d1a

**Comment by ploppyperson** [comment]
If you remove the extra space at the start of the lines where you have uncommented then it should work.

**Comment by yepikaiye** [comment]
Thanks, it worked
